import { SkillData } from "@/model/types";

export const skillDataList: SkillData[] = [
  {
    image: "/skillIcons/HTML.svg",
    alt: "HTML, 클릭하여 기술 상세 보기",
    category: "lang",
    skillName: "HTML",
    description: "웹 페이지의 기본 뼈대를 만들고, 콘텐츠를 넣을 수 있습니다",
  },
  {
    image: "/skillIcons/CSS.svg",
    alt: "CSS, 클릭하여 기술 상세 보기",
    category: "lang",
    skillName: "CSS",
    description: "원하는 디자인의 웹 페이지를 구현할 수 있습니다",
  },
  {
    image: "/skillIcons/JavaScript.svg",
    alt: "JavaScript, 클릭하여 기술 상세 보기",
    category: "lang",
    skillName: "JavaScript",
    description: "동적인 웹사이트를 구현 할 수 있습니다",
  },
  {
    image: "/skillIcons/TypeScript.svg",
    alt: "TypeScript, 클릭하여 기술 상세 보기",
    category: "lang",
    skillName: "TypeScript",
    description: "타입을 적절하게 활용해서 안정적인 개발이 가능합니다",
  },
  {
    image: "/skillIcons/React-Dark.svg",
    alt: "React, 클릭하여 기술 상세 보기",
    category: "framework",
    skillName: "React",
    description: "재사용 가능한 UI를 구현할 수 있습니다",
  },
  {
    image: "/skillIcons/NextJS-Dark.svg",
    alt: "Next.js, 클릭하여 기술 상세 보기",
    category: "framework",
    skillName: "Next.js",
    description: "SEO 최적화 및 벡엔드를 구현할 수 있습니다",
  },
  {
    image: "/skillIcons/StyledComponents.svg",
    alt: "Styled Components, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Styled Components",
    description: "React 컴포넌트에 스타일을 적용 가능합니다",
  },
  {
    image: "/skillIcons/TailwindCSS-Dark.svg",
    alt: "Tailwind CSS, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Tailwind CSS",
    description: "빠르게 반응형 디자인을 만들 수 있습니다",
  },

  {
    image: "/skillIcons/Redux.svg",
    alt: "Redux toolkit, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Redux-toolkit",
    description: "프론트엔드 상태 관리를 위해 사용할 수 있습니다",
  },
  {
    image: "/skillIcons/zustand.png",
    alt: "Zustand, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Zustand",
    description: "프론트엔드 상태 관리를 위해 사용할 수 있습니다",
  },
  {
    image: "/skillIcons/react-query.png",
    alt: "React query, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "React Query",
    description: "서버 상태 관리를 위해 사용할 수 있습니다",
  },
  {
    image: "/skillIcons/MongoDB.svg",
    alt: "Mongo DB, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Mongo DB",
    description: "Next.js와 함께 사용하여 데이터를 저장하고 관리할 수 있습니다",
  },
  {
    image: "/skillIcons/Figma-Light.svg",
    alt: "Figma, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Figma",
    description: "기획 시 UI 디자인을 간단히 그리고 이해할 수 있습니다",
  },
  {
    image: "/skillIcons/공공데이터.jpg",
    alt: "공공데이터 API, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "공공데이터 API",
    description: "정부에서 제공하는 공공데이터 API들을 사용할 수 있습니다",
  },
  {
    image: "/skillIcons/ChatGPT.svg",
    alt: "ChatGPT API, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "ChatGPT API",
    description: "인공지능 챗봇 및 이미지 생성 기능을 구현 가능합니다",
  },
  {
    image: "/skillIcons/socket.jpg",
    alt: "Socket.io, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Socket.io",
    description: "웹소켓 기반의 실시간 양방향 통신 기능을 구현할 수 있습니다",
  },
  {
    image: "/skillIcons/PWA.png",
    alt: "PWA, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "PWA",
    description:
      "웹프로젝트에 PWA를 적용해 모바일에서 사용가능한 웹뷰앱으로 만들 수 있습니다",
  },
  {
    image: "/skillIcons/vercel.jpg",
    alt: "Vercel, 클릭하여 기술 상세 보기",
    category: "etc",
    skillName: "Vercel",
    description: "프로젝트를 효율적으로 배포하고 관리할 수 있습니다",
  },
];
